# Generated by Django 4.2.7 on 2025-09-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportPersonnalise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("ventes", "Ventes"),
                            ("stock", "Stock"),
                            ("clients", "Clients"),
                            ("financier", "Financier"),
                            ("projets", "Projets"),
                            ("performance", "Performance"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=20,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration du rapport (filtres, colonnes, etc.)",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("manuel", "Manuel"),
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="manuel",
                        max_length=20,
                        verbose_name="Fréquence",
                    ),
                ),
                (
                    "planification",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration de la planification",
                        verbose_name="Planification",
                    ),
                ),
                (
                    "derniere_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière exécution"
                    ),
                ),
                (
                    "prochaine_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prochaine exécution"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "partage",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration du partage",
                        verbose_name="Partage",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport personnalisé",
                "verbose_name_plural": "Rapports personnalisés",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionRapport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "duree",
                    models.DurationField(blank=True, null=True, verbose_name="Durée"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("erreur", "Erreur"),
                            ("annule", "Annulé"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_lignes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de lignes"
                    ),
                ),
                (
                    "taille_fichier",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Taille du fichier"
                    ),
                ),
                (
                    "chemin_fichier",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Chemin du fichier"
                    ),
                ),
                (
                    "message_erreur",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="analytics.rapportpersonnalise",
                        verbose_name="Rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exécution rapport",
                "verbose_name_plural": "Exécutions rapport",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Sauvegarde",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "type_sauvegarde",
                    models.CharField(
                        choices=[
                            ("complete", "Complète"),
                            ("incrementale", "Incrémentale"),
                            ("differentielle", "Différentielle"),
                            ("donnees_seules", "Données seules"),
                            ("configuration", "Configuration"),
                        ],
                        max_length=20,
                        verbose_name="Type de sauvegarde",
                    ),
                ),
                (
                    "chemin_fichier",
                    models.CharField(max_length=500, verbose_name="Chemin du fichier"),
                ),
                (
                    "taille_fichier",
                    models.BigIntegerField(verbose_name="Taille du fichier"),
                ),
                ("checksum", models.CharField(max_length=64, verbose_name="Checksum")),
                (
                    "date_debut",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "duree",
                    models.DurationField(blank=True, null=True, verbose_name="Durée"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("erreur", "Erreur"),
                            ("corrompue", "Corrompue"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "automatique",
                    models.BooleanField(default=True, verbose_name="Automatique"),
                ),
                (
                    "restaurable",
                    models.BooleanField(default=True, verbose_name="Restaurable"),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sauvegarde",
                "verbose_name_plural": "Sauvegardes",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["entreprise", "type_sauvegarde"],
                        name="analytics_s_entrepr_b12a92_idx",
                    ),
                    models.Index(
                        fields=["statut", "date_creation"],
                        name="analytics_s_statut_6ba390_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetriquePerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_metrique",
                    models.CharField(
                        choices=[
                            ("ventes_jour", "Ventes du jour"),
                            ("ventes_semaine", "Ventes de la semaine"),
                            ("ventes_mois", "Ventes du mois"),
                            ("clients_actifs", "Clients actifs"),
                            ("produits_populaires", "Produits populaires"),
                            ("marge_moyenne", "Marge moyenne"),
                            ("taux_conversion", "Taux de conversion"),
                            ("panier_moyen", "Panier moyen"),
                        ],
                        max_length=30,
                        verbose_name="Type de métrique",
                    ),
                ),
                (
                    "valeur_numerique",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valeur numérique",
                    ),
                ),
                (
                    "valeur_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Valeur pourcentage",
                    ),
                ),
                (
                    "valeur_json",
                    models.JSONField(blank=True, null=True, verbose_name="Valeur JSON"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "valeur_precedente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valeur précédente",
                    ),
                ),
                (
                    "evolution_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Évolution (%)",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrepreneur",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrique de performance",
                "verbose_name_plural": "Métriques de performance",
                "ordering": ["-date_creation"],
                "unique_together": {
                    ("type_metrique", "entrepreneur", "date_debut", "date_fin")
                },
            },
        ),
    ]
