# Generated by Django 4.2.7 on 2025-09-15 16:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
        ("products", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandeFournisseur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de commande"
                    ),
                ),
                (
                    "date_commande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de commande"
                    ),
                ),
                (
                    "date_livraison_prevue",
                    models.DateField(verbose_name="Date de livraison prévue"),
                ),
                (
                    "date_livraison_reelle",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison réelle"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoyee", "Envoyée"),
                            ("confirmee", "Confirmée"),
                            ("partiellement_livree", "Partiellement livrée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "sous_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "tva_montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total TTC",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "evaluation",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Évaluation",
                    ),
                ),
                (
                    "commentaire_evaluation",
                    models.TextField(blank=True, verbose_name="Commentaire évaluation"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande fournisseur",
                "verbose_name_plural": "Commandes fournisseur",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Entrepot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de l'entrepôt"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="Entrepôt principal"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "adresse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.adresse",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrepots",
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrepôt",
                "verbose_name_plural": "Entrepôts",
            },
        ),
        migrations.CreateModel(
            name="InventairePhysique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "numero_inventaire",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro d'inventaire"
                    ),
                ),
                ("date_planifiee", models.DateTimeField(verbose_name="Date planifiée")),
                (
                    "date_debut",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("valide", "Validé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventaires",
                        to="inventory.entrepot",
                        verbose_name="Entrepôt",
                    ),
                ),
                (
                    "equipe",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inventaires_equipe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventaire physique",
                "verbose_name_plural": "Inventaires physiques",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TransfertStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "numero_transfert",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de transfert"
                    ),
                ),
                (
                    "date_expedition",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expédition"
                    ),
                ),
                (
                    "date_reception",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réception"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepot_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_entrants",
                        to="inventory.entrepot",
                        verbose_name="Entrepôt destination",
                    ),
                ),
                (
                    "entrepot_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferts_sortants",
                        to="inventory.entrepot",
                        verbose_name="Entrepôt source",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert de stock",
                "verbose_name_plural": "Transferts de stock",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "quantite_physique",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité physique"
                    ),
                ),
                (
                    "quantite_reservee",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité réservée"
                    ),
                ),
                (
                    "quantite_en_commande",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité en commande"
                    ),
                ),
                (
                    "cout_unitaire_moyen",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coût unitaire moyen",
                    ),
                ),
                (
                    "date_derniere_entree",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière entrée"
                    ),
                ),
                (
                    "date_derniere_sortie",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière sortie"
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Emplacement"
                    ),
                ),
                (
                    "zone",
                    models.CharField(blank=True, max_length=50, verbose_name="Zone"),
                ),
                (
                    "allee",
                    models.CharField(blank=True, max_length=20, verbose_name="Allée"),
                ),
                (
                    "etagere",
                    models.CharField(blank=True, max_length=20, verbose_name="Étagère"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory.entrepot",
                        verbose_name="Entrepôt",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée"),
                            ("sortie", "Sortie"),
                            ("transfert", "Transfert"),
                            ("ajustement", "Ajustement"),
                            ("reservation", "Réservation"),
                            ("liberation", "Libération"),
                        ],
                        max_length=20,
                        verbose_name="Type de mouvement",
                    ),
                ),
                ("quantite", models.IntegerField(verbose_name="Quantité")),
                (
                    "quantite_avant",
                    models.PositiveIntegerField(verbose_name="Quantité avant"),
                ),
                (
                    "quantite_apres",
                    models.PositiveIntegerField(verbose_name="Quantité après"),
                ),
                (
                    "reference_document",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence document"
                    ),
                ),
                (
                    "cout_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Coût unitaire",
                    ),
                ),
                ("motif", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="inventory.stock",
                        verbose_name="Stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LigneTransfert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "quantite_demandee",
                    models.PositiveIntegerField(verbose_name="Quantité demandée"),
                ),
                (
                    "quantite_expediee",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité expédiée"
                    ),
                ),
                (
                    "quantite_recue",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité reçue"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "transfert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventory.transfertstock",
                        verbose_name="Transfert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de transfert",
                "verbose_name_plural": "Lignes de transfert",
            },
        ),
        migrations.CreateModel(
            name="LigneInventaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "quantite_theorique",
                    models.PositiveIntegerField(verbose_name="Quantité théorique"),
                ),
                (
                    "quantite_comptee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Quantité comptée"
                    ),
                ),
                ("ecart", models.IntegerField(default=0, verbose_name="Écart")),
                ("verifie", models.BooleanField(default=False, verbose_name="Vérifié")),
                (
                    "date_verification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "inventaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventory.inventairephysique",
                        verbose_name="Inventaire",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "verifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'inventaire",
                "verbose_name_plural": "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name="LigneCommandeFournisseur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "quantite_commandee",
                    models.PositiveIntegerField(verbose_name="Quantité commandée"),
                ),
                (
                    "quantite_livree",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité livrée"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "remise_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="inventory.commandefournisseur",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne commande fournisseur",
                "verbose_name_plural": "Lignes commande fournisseur",
            },
        ),
        migrations.AddField(
            model_name="commandefournisseur",
            name="entrepot_livraison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.entrepot",
                verbose_name="Entrepôt de livraison",
            ),
        ),
        migrations.AddField(
            model_name="commandefournisseur",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes",
                to="products.fournisseur",
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="commandefournisseur",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modifie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["produit", "entrepot"], name="inventory_s_produit_d0d921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["quantite_physique"], name="inventory_s_quantit_ca0fa1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("produit", "entrepot")},
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["stock", "date_creation"], name="inventory_m_stock_i_728fe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["type_mouvement", "date_creation"],
                name="inventory_m_type_mo_06c8f3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lignetransfert",
            unique_together={("transfert", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="ligneinventaire",
            unique_together={("inventaire", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="lignecommandefournisseur",
            unique_together={("commande", "produit")},
        ),
        migrations.AlterUniqueTogether(
            name="entrepot",
            unique_together={("entreprise", "code")},
        ),
        migrations.AddIndex(
            model_name="commandefournisseur",
            index=models.Index(
                fields=["fournisseur", "statut"], name="inventory_c_fournis_ef5e97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commandefournisseur",
            index=models.Index(
                fields=["date_livraison_prevue"], name="inventory_c_date_li_00ee31_idx"
            ),
        ),
    ]
