# Generated by Django 4.2.7 on 2025-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commandefournisseur",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="commandefournisseur",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="entrepot",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="entrepot",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="inventairephysique",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="inventairephysique",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="lignecommandefournisseur",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="lignecommandefournisseur",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="ligneinventaire",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="ligneinventaire",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="lignetransfert",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="lignetransfert",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="mouvementstock",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="mouvementstock",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="transfertstock",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="transfertstock",
            name="modifie_par",
        ),
        migrations.AddField(
            model_name="commandefournisseur",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="commandefournisseur",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="entrepot",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="entrepot",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="inventairephysique",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="inventairephysique",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="lignecommandefournisseur",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="lignecommandefournisseur",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="ligneinventaire",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="ligneinventaire",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="lignetransfert",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="lignetransfert",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="transfertstock",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="transfertstock",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
    ]
