# Generated by Django 4.2.7 on 2025-09-15 16:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "__first__"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du projet")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "code_projet",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code projet"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin_prevue",
                    models.DateField(verbose_name="Date de fin prévue"),
                ),
                (
                    "date_fin_reelle",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin réelle"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("en_attente", "En attente"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "budget_prevu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Budget prévu",
                    ),
                ),
                (
                    "budget_consomme",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Budget consommé",
                    ),
                ),
                (
                    "marge_prevue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Marge prévue",
                    ),
                ),
                (
                    "marge_reelle",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Marge réelle",
                    ),
                ),
                (
                    "pourcentage_completion",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Pourcentage de completion",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "risques_identifies",
                    models.JSONField(default=list, verbose_name="Risques identifiés"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projets",
                        to="customers.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True, to="core.document", verbose_name="Documents"
                    ),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets_entrepreneur",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrepreneur",
                    ),
                ),
                (
                    "equipe",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projets_equipe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projets_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TacheProjet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la tâche"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date_debut", models.DateTimeField(verbose_name="Date de début")),
                ("date_fin", models.DateTimeField(verbose_name="Date de fin")),
                (
                    "date_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de completion"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("en_attente", "En attente"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="a_faire",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                ("temps_estime", models.DurationField(verbose_name="Temps estimé")),
                (
                    "temps_reel",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Temps réel"
                    ),
                ),
                (
                    "cout_prevu",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Coût prévu",
                    ),
                ),
                (
                    "cout_reel",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Coût réel",
                    ),
                ),
                (
                    "pourcentage_completion",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Pourcentage de completion",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taches_assignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="projects.projet",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "taches_prerequises",
                    models.ManyToManyField(
                        blank=True,
                        to="projects.tacheprojet",
                        verbose_name="Tâches prérequises",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche de projet",
                "verbose_name_plural": "Tâches de projet",
                "ordering": ["date_debut"],
                "indexes": [
                    models.Index(
                        fields=["projet", "statut"],
                        name="projects_ta_projet__6a7362_idx",
                    ),
                    models.Index(
                        fields=["assignee", "statut"],
                        name="projects_ta_assigne_9faa63_idx",
                    ),
                    models.Index(
                        fields=["date_debut", "date_fin"],
                        name="projects_ta_date_de_fd89f8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="projet",
            index=models.Index(
                fields=["entrepreneur", "statut"], name="projects_pr_entrepr_f92058_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projet",
            index=models.Index(
                fields=["client", "statut"], name="projects_pr_client__e5eae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projet",
            index=models.Index(
                fields=["date_debut", "date_fin_prevue"],
                name="projects_pr_date_de_237838_idx",
            ),
        ),
    ]
