# Generated by Django 4.2.7 on 2025-09-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "titre_template",
                    models.CharField(max_length=200, verbose_name="Template titre"),
                ),
                ("message_template", models.TextField(verbose_name="Template message")),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Succès"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("system", "Système"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=20,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "canaux_actifs",
                    models.JSONField(
                        default=list,
                        help_text="Liste des canaux actifs pour ce template",
                        verbose_name="Canaux actifs",
                    ),
                ),
                (
                    "evenement_declencheur",
                    models.CharField(
                        choices=[
                            ("vente_creee", "Vente créée"),
                            ("paiement_recu", "Paiement reçu"),
                            ("stock_bas", "Stock bas"),
                            ("projet_termine", "Projet terminé"),
                            ("client_inactif", "Client inactif"),
                            ("facture_impayee", "Facture impayée"),
                            ("nouveau_client", "Nouveau client"),
                            ("anniversaire_client", "Anniversaire client"),
                        ],
                        max_length=100,
                        verbose_name="Événement déclencheur",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Conditions pour déclencher la notification",
                        verbose_name="Conditions",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de notification",
                "verbose_name_plural": "Templates de notification",
            },
        ),
        migrations.CreateModel(
            name="PreferenceNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "notifications_app",
                    models.BooleanField(default=True, verbose_name="Notifications app"),
                ),
                (
                    "notifications_email",
                    models.BooleanField(
                        default=True, verbose_name="Notifications email"
                    ),
                ),
                (
                    "notifications_sms",
                    models.BooleanField(
                        default=False, verbose_name="Notifications SMS"
                    ),
                ),
                (
                    "notifications_push",
                    models.BooleanField(
                        default=True, verbose_name="Notifications push"
                    ),
                ),
                (
                    "alertes_stock",
                    models.BooleanField(default=True, verbose_name="Alertes stock"),
                ),
                (
                    "nouvelles_ventes",
                    models.BooleanField(default=True, verbose_name="Nouvelles ventes"),
                ),
                (
                    "paiements_recus",
                    models.BooleanField(default=True, verbose_name="Paiements reçus"),
                ),
                (
                    "projets_updates",
                    models.BooleanField(
                        default=True, verbose_name="Mises à jour projets"
                    ),
                ),
                (
                    "marketing",
                    models.BooleanField(default=False, verbose_name="Marketing"),
                ),
                (
                    "heure_debut",
                    models.TimeField(default="08:00", verbose_name="Heure de début"),
                ),
                (
                    "heure_fin",
                    models.TimeField(default="20:00", verbose_name="Heure de fin"),
                ),
                (
                    "jours_actifs",
                    models.JSONField(
                        default=list,
                        help_text="Jours de la semaine actifs (0=lundi, 6=dimanche)",
                        verbose_name="Jours actifs",
                    ),
                ),
                (
                    "frequence_resume",
                    models.CharField(
                        choices=[
                            ("jamais", "Jamais"),
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                        ],
                        default="quotidien",
                        max_length=20,
                        verbose_name="Fréquence du résumé",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Succès"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("system", "Système"),
                            ("marketing", "Marketing"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("app", "Application"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("webhook", "Webhook"),
                        ],
                        default="app",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("lue", models.BooleanField(default=False, verbose_name="Lue")),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="URL d'action"),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Label d'action"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="Métadonnées"),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "groupe",
                    models.CharField(blank=True, max_length=100, verbose_name="Groupe"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "lue", "date_creation"],
                        name="notificatio_utilisa_07028c_idx",
                    ),
                    models.Index(
                        fields=["type", "date_creation"],
                        name="notificatio_type_32c0dc_idx",
                    ),
                    models.Index(
                        fields=["groupe", "date_creation"],
                        name="notificatio_groupe_ec2a42_idx",
                    ),
                ],
            },
        ),
    ]
