# Generated by Django 4.2.7 on 2025-09-15 16:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "__first__"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilisateurPersonnalise",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_utilisateur",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("entrepreneur", "Entrepreneur"),
                            ("client", "Client"),
                            ("employe", "Employé"),
                            ("support", "Support"),
                        ],
                        max_length=20,
                        verbose_name="Type d'utilisateur",
                    ),
                ),
                (
                    "entreprise_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID de l'entreprise"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="avatars/", verbose_name="Avatar"
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculin"),
                            ("F", "Féminin"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "date_derniere_connexion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière connexion"
                    ),
                ),
                (
                    "nombre_connexions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de connexions"
                    ),
                ),
                (
                    "adresse_ip_derniere",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dernière adresse IP"
                    ),
                ),
                (
                    "mfa_actif",
                    models.BooleanField(default=False, verbose_name="MFA activé"),
                ),
                (
                    "secret_mfa",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Secret MFA"
                    ),
                ),
                (
                    "codes_recuperation",
                    models.JSONField(
                        default=list, verbose_name="Codes de récupération"
                    ),
                ),
                (
                    "theme_interface",
                    models.CharField(
                        choices=[
                            ("light", "Clair"),
                            ("dark", "Sombre"),
                            ("auto", "Automatique"),
                        ],
                        default="light",
                        max_length=10,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "Anglais"),
                            ("ar", "Arabe"),
                            ("wo", "Wolof"),
                        ],
                        default="fr",
                        max_length=2,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "fuseau_horaire",
                    models.CharField(
                        choices=[
                            ("Africa/Dakar", "Dakar (GMT+0)"),
                            ("Africa/Casablanca", "Casablanca (GMT+1)"),
                            ("Europe/Paris", "Paris (GMT+1)"),
                            ("America/New_York", "New York (GMT-5)"),
                        ],
                        default="Africa/Dakar",
                        max_length=50,
                        verbose_name="Fuseau horaire",
                    ),
                ),
                (
                    "preferences_notifications_json",
                    models.JSONField(
                        default=dict, verbose_name="Préférences de notifications"
                    ),
                ),
                (
                    "notifications_email",
                    models.BooleanField(
                        default=True, verbose_name="Notifications par email"
                    ),
                ),
                (
                    "notifications_sms",
                    models.BooleanField(
                        default=False, verbose_name="Notifications par SMS"
                    ),
                ),
                (
                    "notifications_push",
                    models.BooleanField(
                        default=True, verbose_name="Notifications push"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "competences",
                    models.JSONField(default=list, verbose_name="Compétences"),
                ),
                (
                    "reseaux_sociaux",
                    models.JSONField(default=dict, verbose_name="Réseaux sociaux"),
                ),
                (
                    "points_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Points d'expérience"
                    ),
                ),
                (
                    "niveau",
                    models.PositiveIntegerField(default=1, verbose_name="Niveau"),
                ),
                (
                    "badges",
                    models.JSONField(default=list, verbose_name="Badges obtenus"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "email_verifie",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                (
                    "telephone_verifie",
                    models.BooleanField(
                        default=False, verbose_name="Téléphone vérifié"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "adresse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.adresse",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Code"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("module", models.CharField(max_length=50, verbose_name="Module")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["module", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "systeme",
                    models.BooleanField(default=False, verbose_name="Rôle système"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#6B7280", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="users.permission", verbose_name="Permissions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="UtilisateurRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "entreprise_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID de l'entreprise"
                    ),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.role",
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur-Rôle",
                "verbose_name_plural": "Utilisateurs-Rôles",
                "unique_together": {("utilisateur", "role", "entreprise_id")},
            },
        ),
        migrations.CreateModel(
            name="SessionUtilisateur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="Clé de session"),
                ),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "pays",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Début de session"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de session"
                    ),
                ),
                (
                    "derniere_activite",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "appareil",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Appareil"
                    ),
                ),
                (
                    "navigateur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Navigateur"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateur",
                "ordering": ["-date_debut"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur", "date_debut"],
                        name="users_sessi_utilisa_63cff1_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="users_sessi_session_f37a3b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="utilisateurpersonnalise",
            index=models.Index(
                fields=["type_utilisateur", "statut"],
                name="users_utili_type_ut_c662b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateurpersonnalise",
            index=models.Index(
                fields=["entreprise_id", "type_utilisateur"],
                name="users_utili_entrepr_0ba93a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="utilisateurpersonnalise",
            index=models.Index(
                fields=["email_verifie", "statut"],
                name="users_utili_email_v_356181_idx",
            ),
        ),
    ]
