# Generated by Django 4.2.7 on 2025-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_permission_cree_par_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateurpersonnalise",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
