# Generated by Django 4.2.7 on 2025-09-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_entreprise_plan_abonnement_and_more"),
        ("users", "0003_alter_utilisateurpersonnalise_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateurpersonnalise",
            name="entreprise_id",
        ),
        migrations.AddField(
            model_name="utilisateurpersonnalise",
            name="entreprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.entreprise",
                verbose_name="Entreprise",
            ),
        ),
    ]
