# Generated by Django 4.2.7 on 2025-09-15 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParametreSysteme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "cree_par_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID du créateur"
                    ),
                ),
                (
                    "modifie_par_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID du modificateur"
                    ),
                ),
                (
                    "cle",
                    models.CharField(max_length=100, unique=True, verbose_name="Clé"),
                ),
                ("valeur", models.TextField(verbose_name="Valeur")),
                (
                    "type_valeur",
                    models.CharField(
                        choices=[
                            ("string", "Chaîne"),
                            ("integer", "Entier"),
                            ("float", "Décimal"),
                            ("boolean", "Booléen"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Type de valeur",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "categorie",
                    models.CharField(max_length=50, verbose_name="Catégorie"),
                ),
                (
                    "modifiable",
                    models.BooleanField(default=True, verbose_name="Modifiable"),
                ),
                (
                    "sensible",
                    models.BooleanField(default=False, verbose_name="Sensible"),
                ),
            ],
            options={
                "verbose_name": "Paramètre système",
                "verbose_name_plural": "Paramètres système",
                "indexes": [
                    models.Index(
                        fields=["categorie", "cle"],
                        name="core_parame_categor_87a166_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "utilisateur_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID de l'utilisateur"
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                ("modele", models.CharField(max_length=100, verbose_name="Modèle")),
                (
                    "objet_id",
                    models.CharField(max_length=100, verbose_name="ID de l'objet"),
                ),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données avant"
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données après"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de session"
                    ),
                ),
                (
                    "niveau_risque",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Niveau de risque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["utilisateur_id", "timestamp"],
                        name="core_journa_utilisa_b4ca30_idx",
                    ),
                    models.Index(
                        fields=["modele", "objet_id"],
                        name="core_journa_modele_c9ec96_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="core_journa_action_625793_idx",
                    ),
                    models.Index(
                        fields=["niveau_risque", "timestamp"],
                        name="core_journa_niveau__abe0d5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "cree_par_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID du créateur"
                    ),
                ),
                (
                    "modifie_par_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID du modificateur"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de l'adresse"),
                ),
                (
                    "adresse_ligne1",
                    models.CharField(max_length=255, verbose_name="Adresse ligne 1"),
                ),
                (
                    "adresse_ligne2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 2"
                    ),
                ),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                ("region", models.CharField(max_length=100, verbose_name="Région")),
                (
                    "pays",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Point géographique",
                    ),
                ),
                (
                    "type_adresse",
                    models.CharField(
                        choices=[
                            ("domicile", "Domicile"),
                            ("travail", "Travail"),
                            ("facturation", "Facturation"),
                            ("livraison", "Livraison"),
                            ("autre", "Autre"),
                        ],
                        default="domicile",
                        max_length=20,
                        verbose_name="Type d'adresse",
                    ),
                ),
                (
                    "principale",
                    models.BooleanField(
                        default=False, verbose_name="Adresse principale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "indexes": [
                    models.Index(
                        fields=["ville", "region"], name="core_adress_ville_696232_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="core_adress_latitud_b74b55_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "cree_par_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID du créateur"
                    ),
                ),
                (
                    "modifie_par_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID du modificateur"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "type_mime",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type MIME"
                    ),
                ),
                (
                    "taille",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Taille en octets"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("facture", "Facture"),
                            ("devis", "Devis"),
                            ("contrat", "Contrat"),
                            ("rapport", "Rapport"),
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("audio", "Audio"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                        verbose_name="Type de document",
                    ),
                ),
                ("public", models.BooleanField(default=False, verbose_name="Public")),
                (
                    "mot_de_passe",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mot de passe"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "document_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.document",
                        verbose_name="Document parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "indexes": [
                    models.Index(
                        fields=["type_document", "date_creation"],
                        name="core_docume_type_do_630faf_idx",
                    ),
                    models.Index(
                        fields=["public", "supprime"],
                        name="core_docume_public_5040fb_idx",
                    ),
                ],
            },
        ),
    ]
