# Generated by Django 4.2.7 on 2025-09-15 16:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "type_modele",
                    models.CharField(
                        choices=[
                            ("recommendation", "Recommandation"),
                            ("prediction_ventes", "Prédiction ventes"),
                            ("detection_anomalies", "Détection anomalies"),
                            ("segmentation_clients", "Segmentation clients"),
                            ("optimisation_prix", "Optimisation prix"),
                            ("chatbot", "Chatbot"),
                            ("ocr", "OCR"),
                            ("reconnaissance_vocale", "Reconnaissance vocale"),
                        ],
                        max_length=30,
                        verbose_name="Type de modèle",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "parametres",
                    models.JSONField(default=dict, verbose_name="Paramètres"),
                ),
                (
                    "hyperparametres",
                    models.JSONField(default=dict, verbose_name="Hyperparamètres"),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Précision",
                    ),
                ),
                (
                    "rappel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Rappel",
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="F1 Score",
                    ),
                ),
                (
                    "date_entrainement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'entraînement"
                    ),
                ),
                (
                    "taille_dataset",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Taille du dataset"
                    ),
                ),
                (
                    "duree_entrainement",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée d'entraînement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("entrainement", "En entraînement"),
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("erreur", "Erreur"),
                            ("obsolete", "Obsolète"),
                        ],
                        default="inactif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_predictions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de prédictions"
                    ),
                ),
                (
                    "derniere_utilisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle IA",
                "verbose_name_plural": "Modèles IA",
                "unique_together": {("nom", "version")},
            },
        ),
        migrations.CreateModel(
            name="RecommandationProduit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_recommendation",
                    models.CharField(
                        choices=[
                            ("similaires", "Produits similaires"),
                            ("complementaires", "Produits complémentaires"),
                            ("upsell", "Upsell"),
                            ("cross_sell", "Cross-sell"),
                            ("personnalisees", "Recommandations personnalisées"),
                        ],
                        max_length=20,
                        verbose_name="Type de recommandation",
                    ),
                ),
                (
                    "contexte",
                    models.JSONField(
                        default=dict, verbose_name="Contexte de la recommandation"
                    ),
                ),
                (
                    "nombre_vues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "nombre_clics",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de clics"
                    ),
                ),
                (
                    "nombre_conversions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de conversions"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_source",
                        to="products.produit",
                        verbose_name="Produit source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation produit",
                "verbose_name_plural": "Recommandations produit",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="RecommandationScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Score de recommandation",
                    ),
                ),
                ("rang", models.PositiveIntegerField(verbose_name="Rang")),
                (
                    "raisons",
                    models.JSONField(
                        default=list, verbose_name="Raisons de la recommandation"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_engine.recommandationproduit",
                        verbose_name="Recommandation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score de recommandation",
                "verbose_name_plural": "Scores de recommandation",
                "ordering": ["rang"],
                "unique_together": {("recommendation", "produit")},
            },
        ),
        migrations.AddField(
            model_name="recommandationproduit",
            name="produits_recommandes",
            field=models.ManyToManyField(
                through="ai_engine.RecommandationScore",
                to="products.produit",
                verbose_name="Produits recommandés",
            ),
        ),
        migrations.AddField(
            model_name="recommandationproduit",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="PredictionVente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "ventes_predites",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ventes prédites"
                    ),
                ),
                (
                    "confiance",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Niveau de confiance",
                    ),
                ),
                (
                    "predictions_produits",
                    models.JSONField(
                        default=dict, verbose_name="Prédictions par produit"
                    ),
                ),
                (
                    "facteurs_cles",
                    models.JSONField(default=list, verbose_name="Facteurs clés"),
                ),
                (
                    "ventes_reelles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Ventes réelles",
                    ),
                ),
                (
                    "precision_prediction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="Précision de la prédiction",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrepreneur",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_engine.modeleia",
                        verbose_name="Modèle utilisé",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédiction de vente",
                "verbose_name_plural": "Prédictions de vente",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, verbose_name="ID de session"),
                ),
                (
                    "messages",
                    models.JSONField(
                        default=list, verbose_name="Messages de la conversation"
                    ),
                ),
                (
                    "intention_detectee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("question_produit", "Question produit"),
                            ("statut_commande", "Statut commande"),
                            ("probleme_paiement", "Problème paiement"),
                            ("support_technique", "Support technique"),
                            ("demande_generale", "Demande générale"),
                        ],
                        max_length=50,
                        verbose_name="Intention détectée",
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positif", "Positif"),
                            ("neutre", "Neutre"),
                            ("negatif", "Négatif"),
                        ],
                        max_length=20,
                        verbose_name="Sentiment",
                    ),
                ),
                ("resolu", models.BooleanField(default=False, verbose_name="Résolu")),
                (
                    "transfere_humain",
                    models.BooleanField(
                        default=False, verbose_name="Transféré à un humain"
                    ),
                ),
                (
                    "satisfaction",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Satisfaction",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation chatbot",
                "verbose_name_plural": "Conversations chatbot",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="AnalyseComportement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "pages_visitees",
                    models.JSONField(default=list, verbose_name="Pages visitées"),
                ),
                (
                    "produits_vus",
                    models.JSONField(default=list, verbose_name="Produits vus"),
                ),
                (
                    "temps_session",
                    models.DurationField(verbose_name="Temps de session"),
                ),
                (
                    "actions_effectuees",
                    models.JSONField(default=list, verbose_name="Actions effectuées"),
                ),
                (
                    "segment_comportemental",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("explorateur", "Explorateur"),
                            ("decideur_rapide", "Décideur rapide"),
                            ("comparateur", "Comparateur"),
                            ("fidele", "Fidèle"),
                            ("occasionnel", "Occasionnel"),
                        ],
                        max_length=50,
                        verbose_name="Segment comportemental",
                    ),
                ),
                (
                    "score_engagement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Score d'engagement",
                    ),
                ),
                (
                    "probabilite_achat",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Probabilité d'achat",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse comportement",
                "verbose_name_plural": "Analyses comportement",
                "ordering": ["-date_creation"],
            },
        ),
    ]
