# Generated by Django 4.2.7 on 2025-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionutilisateur",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="sessionutilisateur",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="tokenapi",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="tokenapi",
            name="modifie_par",
        ),
        migrations.AddField(
            model_name="sessionutilisateur",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="sessionutilisateur",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="tokenapi",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="tokenapi",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
    ]
