# Generated by Django 4.2.7 on 2025-09-15 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAbonnement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom du plan")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "prix_mensuel",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix mensuel"
                    ),
                ),
                (
                    "prix_annuel",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix annuel"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("XOF", "Franc CFA (XOF)"),
                            ("EUR", "Euro (EUR)"),
                            ("USD", "Dollar US (USD)"),
                            ("GBP", "Livre Sterling (GBP)"),
                        ],
                        default="XOF",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "max_utilisateurs",
                    models.PositiveIntegerField(
                        verbose_name="Nombre max d'utilisateurs"
                    ),
                ),
                (
                    "max_produits",
                    models.PositiveIntegerField(verbose_name="Nombre max de produits"),
                ),
                (
                    "max_ventes_mensuelles",
                    models.PositiveIntegerField(
                        verbose_name="Nombre max de ventes mensuelles"
                    ),
                ),
                (
                    "stockage_gb",
                    models.PositiveIntegerField(verbose_name="Stockage en GB"),
                ),
                (
                    "fonctionnalites",
                    models.JSONField(
                        default=dict, verbose_name="Fonctionnalités incluses"
                    ),
                ),
                (
                    "populaire",
                    models.BooleanField(default=False, verbose_name="Plan populaire"),
                ),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
                "ordering": ["ordre_affichage", "prix_mensuel"],
            },
        ),
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "nom_commercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom commercial"
                    ),
                ),
                (
                    "secteur_activite",
                    models.CharField(
                        choices=[
                            ("commerce", "Commerce"),
                            ("services", "Services"),
                            ("industrie", "Industrie"),
                            ("agriculture", "Agriculture"),
                            ("technologie", "Technologie"),
                            ("sante", "Santé"),
                            ("education", "Éducation"),
                            ("transport", "Transport"),
                            ("immobilier", "Immobilier"),
                            ("finance", "Finance"),
                            ("tourisme", "Tourisme"),
                            ("artisanat", "Artisanat"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Secteur d'activité",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                ("adresse_complete", models.TextField(verbose_name="Adresse complète")),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                ("region", models.CharField(max_length=100, verbose_name="Région")),
                (
                    "pays",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="SIRET/NINEA",
                    ),
                ),
                (
                    "tva_intracommunautaire",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TVA intracommunautaire"
                    ),
                ),
                (
                    "forme_juridique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sarl", "SARL"),
                            ("sa", "SA"),
                            ("sas", "SAS"),
                            ("eurl", "EURL"),
                            ("ei", "Entreprise Individuelle"),
                            ("auto_entrepreneur", "Auto-entrepreneur"),
                            ("association", "Association"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Forme juridique",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="entreprises/logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "couleur_primaire",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Couleur primaire"
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        default="#10B981",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "devise_principale",
                    models.CharField(
                        choices=[
                            ("XOF", "Franc CFA (XOF)"),
                            ("EUR", "Euro (EUR)"),
                            ("USD", "Dollar US (USD)"),
                            ("GBP", "Livre Sterling (GBP)"),
                        ],
                        default="XOF",
                        max_length=3,
                        verbose_name="Devise principale",
                    ),
                ),
                (
                    "fuseau_horaire",
                    models.CharField(
                        choices=[
                            ("Africa/Dakar", "Dakar (GMT+0)"),
                            ("Africa/Casablanca", "Casablanca (GMT+1)"),
                            ("Europe/Paris", "Paris (GMT+1)"),
                            ("America/New_York", "New York (GMT-5)"),
                        ],
                        default="Africa/Dakar",
                        max_length=50,
                        verbose_name="Fuseau horaire",
                    ),
                ),
                (
                    "date_debut_abonnement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Début d'abonnement"
                    ),
                ),
                (
                    "date_fin_abonnement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin d'abonnement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_employes",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre d'employés"
                    ),
                ),
                (
                    "chiffre_affaires_annuel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Chiffre d'affaires annuel",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(default=dict, verbose_name="Préférences"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "plan_abonnement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.planabonnement",
                        verbose_name="Plan d'abonnement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "indexes": [
                    models.Index(
                        fields=["secteur_activite", "statut"],
                        name="companies_e_secteur_0db07b_idx",
                    ),
                    models.Index(
                        fields=["ville", "region"], name="companies_e_ville_b703c6_idx"
                    ),
                ],
            },
        ),
    ]
