# Generated by Django 4.2.7 on 2025-09-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_remove_entreprise_cree_par_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="plan_abonnement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="companies.planabonnement",
                verbose_name="Plan d'abonnement",
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="secteur_activite",
            field=models.CharField(
                choices=[
                    ("commerce_general", "Commerce Général"),
                    ("commerce_alimentaire", "Commerce Alimentaire"),
                    ("commerce_textile", "Commerce Textile & Vêtements"),
                    ("commerce_electronique", "Commerce Électronique & High-Tech"),
                    ("commerce_pharmaceutique", "Commerce Pharmaceutique"),
                    ("commerce_automobile", "Commerce Automobile"),
                    ("commerce_immobilier", "Commerce Immobilier"),
                    ("commerce_artisanat", "Commerce Artisanal"),
                    ("commerce_import_export", "Commerce Import/Export"),
                    ("commerce_retail", "Commerce de Détail"),
                    ("commerce_wholesale", "Commerce de Gros"),
                    ("commerce_online", "Commerce en Ligne"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                verbose_name="Secteur d'activité",
            ),
        ),
    ]
