# Generated by Django 4.2.7 on 2025-09-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("icone", models.CharField(max_length=50, verbose_name="Icône")),
                (
                    "couleur",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Conditions pour obtenir le badge",
                        verbose_name="Conditions",
                    ),
                ),
                (
                    "points_bonus",
                    models.PositiveIntegerField(default=0, verbose_name="Points bonus"),
                ),
                ("rare", models.BooleanField(default=False, verbose_name="Badge rare")),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Classement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type_classement",
                    models.CharField(
                        choices=[
                            ("ventes_mois", "Ventes du mois"),
                            ("points_experience", "Points d'expérience"),
                            ("badges_obtenus", "Badges obtenus"),
                            ("projets_termines", "Projets terminés"),
                            ("satisfaction_client", "Satisfaction client"),
                        ],
                        max_length=30,
                        verbose_name="Type de classement",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "recompenses",
                    models.JSONField(
                        default=dict,
                        help_text="Récompenses par position",
                        verbose_name="Récompenses",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classement",
                "verbose_name_plural": "Classements",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Defi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "type_defi",
                    models.CharField(
                        choices=[
                            ("quotidien", "Quotidien"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("special", "Spécial"),
                            ("saisonnier", "Saisonnier"),
                        ],
                        max_length=20,
                        verbose_name="Type de défi",
                    ),
                ),
                (
                    "objectif",
                    models.JSONField(
                        default=dict,
                        help_text="Objectif à atteindre",
                        verbose_name="Objectif",
                    ),
                ),
                (
                    "points_recompense",
                    models.PositiveIntegerField(verbose_name="Points de récompense"),
                ),
                ("date_debut", models.DateTimeField(verbose_name="Date de début")),
                ("date_fin", models.DateTimeField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "badge_recompense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamification.badge",
                        verbose_name="Badge récompense",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Défi",
                "verbose_name_plural": "Défis",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PositionClassement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="Position")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Score"
                    ),
                ),
                (
                    "position_precedente",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Position précédente"
                    ),
                ),
                ("evolution", models.IntegerField(default=0, verbose_name="Évolution")),
                (
                    "classement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.classement",
                        verbose_name="Classement",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position classement",
                "verbose_name_plural": "Positions classement",
                "ordering": ["position"],
                "unique_together": {("classement", "utilisateur")},
            },
        ),
        migrations.CreateModel(
            name="ParticipationDefi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "progression",
                    models.JSONField(default=dict, verbose_name="Progression"),
                ),
                (
                    "pourcentage_completion",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pourcentage de completion"
                    ),
                ),
                (
                    "date_inscription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "date_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de completion"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("echoue", "Échoué"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "recompense_recue",
                    models.BooleanField(default=False, verbose_name="Récompense reçue"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "defi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.defi",
                        verbose_name="Défi",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation défi",
                "verbose_name_plural": "Participations défi",
                "ordering": ["-date_inscription"],
                "unique_together": {("utilisateur", "defi")},
            },
        ),
        migrations.AddField(
            model_name="defi",
            name="participants",
            field=models.ManyToManyField(
                through="gamification.ParticipationDefi",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.AddField(
            model_name="classement",
            name="participants",
            field=models.ManyToManyField(
                through="gamification.PositionClassement",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.CreateModel(
            name="UtilisateurBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "date_obtention",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'obtention"
                    ),
                ),
                (
                    "raison",
                    models.TextField(blank=True, verbose_name="Raison d'obtention"),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="Visible sur le profil"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.badge",
                        verbose_name="Badge",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge utilisateur",
                "verbose_name_plural": "Badges utilisateur",
                "ordering": ["-date_obtention"],
                "unique_together": {("utilisateur", "badge")},
            },
        ),
    ]
