# Generated by Django 4.2.7 on 2025-09-15 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationExterne",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type_integration",
                    models.CharField(
                        choices=[
                            ("wave_money", "Wave Money"),
                            ("orange_money", "Orange Money"),
                            ("whatsapp_business", "WhatsApp Business"),
                            ("sage_comptabilite", "Sage Comptabilité"),
                            ("quickbooks", "QuickBooks"),
                            ("jumia", "Jumia"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("google_analytics", "Google Analytics"),
                            ("mailchimp", "MailChimp"),
                            ("twilio", "Twilio"),
                        ],
                        max_length=30,
                        verbose_name="Type d'intégration",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="Configuration"),
                ),
                (
                    "credentials",
                    models.JSONField(default=dict, verbose_name="Identifiants"),
                ),
                ("url_api", models.URLField(blank=True, verbose_name="URL API")),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="URL Webhook"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("erreur", "Erreur"),
                            ("configuration", "En configuration"),
                            ("suspendue", "Suspendue"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "derniere_synchronisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                (
                    "nombre_erreurs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'erreurs"
                    ),
                ),
                (
                    "derniere_erreur",
                    models.TextField(blank=True, verbose_name="Dernière erreur"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intégration externe",
                "verbose_name_plural": "Intégrations externes",
                "unique_together": {("entreprise", "type_integration")},
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("url", models.URLField(verbose_name="URL")),
                ("secret", models.CharField(max_length=255, verbose_name="Secret")),
                (
                    "evenements",
                    models.JSONField(
                        default=list,
                        help_text="Liste des événements à écouter",
                        verbose_name="Événements",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Timeout (secondes)"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Nombre de tentatives"
                    ),
                ),
                (
                    "nombre_appels",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'appels"
                    ),
                ),
                (
                    "nombre_succes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de succès"
                    ),
                ),
                (
                    "nombre_echecs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'échecs"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="integrations.integrationexterne",
                        verbose_name="Intégration",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook endpoint",
                "verbose_name_plural": "Webhook endpoints",
            },
        ),
        migrations.CreateModel(
            name="SynchronisationDonnees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_donnees",
                    models.CharField(
                        choices=[
                            ("produits", "Produits"),
                            ("clients", "Clients"),
                            ("ventes", "Ventes"),
                            ("stock", "Stock"),
                            ("commandes", "Commandes"),
                            ("paiements", "Paiements"),
                        ],
                        max_length=50,
                        verbose_name="Type de données",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("export", "Export"),
                            ("bidirectionnel", "Bidirectionnel"),
                        ],
                        max_length=20,
                        verbose_name="Direction",
                    ),
                ),
                ("date_planifiee", models.DateTimeField(verbose_name="Date planifiée")),
                (
                    "date_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'exécution"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("erreur", "Erreur"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_enregistrements",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'enregistrements"
                    ),
                ),
                (
                    "nombre_succes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de succès"
                    ),
                ),
                (
                    "nombre_erreurs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'erreurs"
                    ),
                ),
                (
                    "log_execution",
                    models.TextField(blank=True, verbose_name="Log d'exécution"),
                ),
                (
                    "erreurs_details",
                    models.JSONField(default=list, verbose_name="Détails des erreurs"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integrationexterne",
                        verbose_name="Intégration",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synchronisation données",
                "verbose_name_plural": "Synchronisations données",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LogIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("sync", "Synchronisation"),
                            ("webhook", "Webhook"),
                            ("api_call", "Appel API"),
                            ("error", "Erreur"),
                            ("config", "Configuration"),
                        ],
                        max_length=20,
                        verbose_name="Type d'action",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "donnees_envoyees",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données envoyées"
                    ),
                ),
                (
                    "donnees_recues",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données reçues"
                    ),
                ),
                ("succes", models.BooleanField(default=True, verbose_name="Succès")),
                (
                    "code_reponse",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code de réponse"
                    ),
                ),
                (
                    "message_erreur",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "duree_execution",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée d'exécution"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.integrationexterne",
                        verbose_name="Intégration",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log intégration",
                "verbose_name_plural": "Logs intégration",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["integration", "date_creation"],
                        name="integration_integra_63078a_idx",
                    ),
                    models.Index(
                        fields=["type_action", "succes"],
                        name="integration_type_ac_6adfb0_idx",
                    ),
                ],
            },
        ),
    ]
