# Generated by Django 4.2.7 on 2025-09-15 16:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "code_client",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code client"
                    ),
                ),
                (
                    "type_client",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("professionnel", "Professionnel"),
                            ("entreprise", "Entreprise"),
                        ],
                        default="particulier",
                        max_length=20,
                        verbose_name="Type de client",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "telephone_secondaire",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone secondaire"
                    ),
                ),
                (
                    "entreprise_nom",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                (
                    "secteur_activite",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Secteur d'activité"
                    ),
                ),
                (
                    "adresse_facturation",
                    models.TextField(verbose_name="Adresse de facturation"),
                ),
                (
                    "adresse_livraison",
                    models.TextField(blank=True, verbose_name="Adresse de livraison"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "date_derniere_commande",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière commande"
                    ),
                ),
                (
                    "total_achats",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total des achats",
                    ),
                ),
                (
                    "nombre_commandes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de commandes"
                    ),
                ),
                (
                    "panier_moyen",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Panier moyen",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("regulier", "Régulier"),
                            ("vip", "VIP"),
                            ("inactif", "Inactif"),
                            ("risque", "À risque"),
                        ],
                        default="nouveau",
                        max_length=50,
                        verbose_name="Segment",
                    ),
                ),
                (
                    "score_fidelite",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Score de fidélité"
                    ),
                ),
                (
                    "source_acquisition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("referencement", "Référencement"),
                            ("publicite", "Publicité"),
                            ("reseaux_sociaux", "Réseaux sociaux"),
                            ("bouche_a_oreille", "Bouche à oreille"),
                            ("partenaire", "Partenaire"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Source d'acquisition",
                    ),
                ),
                (
                    "date_acquisition",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'acquisition"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(default=dict, verbose_name="Préférences"),
                ),
                (
                    "preferences_communication",
                    models.JSONField(
                        default=dict,
                        help_text="Préférences de communication (email, SMS, etc.)",
                        verbose_name="Préférences de communication",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "points_fidelite",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Points de fidélité"
                    ),
                ),
                (
                    "niveau_fidelite",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("argent", "Argent"),
                            ("or", "Or"),
                            ("platine", "Platine"),
                            ("diamant", "Diamant"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Niveau de fidélité",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrepreneur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="CampagneMarketing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la campagne"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "type_campagne",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Notification push"),
                            ("courrier", "Courrier"),
                            ("mixte", "Mixte"),
                        ],
                        max_length=20,
                        verbose_name="Type de campagne",
                    ),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="Sujet")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "contenu_html",
                    models.TextField(blank=True, verbose_name="Contenu HTML"),
                ),
                (
                    "segment_cible",
                    models.CharField(
                        choices=[
                            ("tous", "Tous les clients"),
                            ("nouveau", "Nouveaux clients"),
                            ("regulier", "Clients réguliers"),
                            ("vip", "Clients VIP"),
                            ("inactif", "Clients inactifs"),
                            ("personnalise", "Segment personnalisé"),
                        ],
                        default="tous",
                        max_length=50,
                        verbose_name="Segment cible",
                    ),
                ),
                (
                    "criteres_ciblage",
                    models.JSONField(default=dict, verbose_name="Critères de ciblage"),
                ),
                (
                    "date_envoi_prevue",
                    models.DateTimeField(verbose_name="Date d'envoi prévue"),
                ),
                (
                    "date_envoi_reelle",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi réelle"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("suspendue", "Suspendue"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_destinataires",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de destinataires"
                    ),
                ),
                (
                    "nombre_envoyes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre envoyés"
                    ),
                ),
                (
                    "nombre_ouverts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre ouverts"
                    ),
                ),
                (
                    "nombre_clics",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de clics"
                    ),
                ),
                (
                    "nombre_conversions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de conversions"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrepreneur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne marketing",
                "verbose_name_plural": "Campagnes marketing",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="InteractionClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_interaction",
                    models.CharField(
                        choices=[
                            ("appel", "Appel téléphonique"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("visite", "Visite en magasin"),
                            ("chat", "Chat en ligne"),
                            ("reseaux_sociaux", "Réseaux sociaux"),
                            ("courrier", "Courrier"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type d'interaction",
                    ),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="Sujet")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "duree_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "action_requise",
                    models.BooleanField(default=False, verbose_name="Action requise"),
                ),
                (
                    "date_action_prevue",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'action prévue"
                    ),
                ),
                (
                    "action_terminee",
                    models.BooleanField(default=False, verbose_name="Action terminée"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="customers.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction client",
                "verbose_name_plural": "Interactions client",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["client", "date_creation"],
                        name="customers_i_client__2b7caa_idx",
                    ),
                    models.Index(
                        fields=["type_interaction", "date_creation"],
                        name="customers_i_type_in_269aaf_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["entrepreneur", "statut"], name="customers_c_entrepr_2c6a2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["segment", "score_fidelite"],
                name="customers_c_segment_10aaf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="customers_c_email_c1e1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["telephone"], name="customers_c_telepho_19e5a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("entrepreneur", "email")},
        ),
    ]
