# Generated by Django 4.2.7 on 2025-09-15 16:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementMobile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "reference_interne",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence interne"
                    ),
                ),
                (
                    "operateur",
                    models.CharField(
                        choices=[
                            ("wave", "Wave Money"),
                            ("orange_money", "Orange Money"),
                            ("free_money", "Free Money"),
                            ("wizall", "Wizall"),
                            ("joni_joni", "Joni Joni"),
                        ],
                        max_length=20,
                        verbose_name="Opérateur",
                    ),
                ),
                (
                    "numero_telephone",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence transaction"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_initiation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'initiation"
                    ),
                ),
                (
                    "date_confirmation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de confirmation"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "code_confirmation",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code de confirmation"
                    ),
                ),
                (
                    "code_erreur",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code d'erreur"
                    ),
                ),
                (
                    "message_erreur",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "webhook_payload",
                    models.JSONField(default=dict, verbose_name="Payload webhook"),
                ),
                (
                    "webhook_signature",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Signature webhook"
                    ),
                ),
                (
                    "frais_operateur",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais opérateur",
                    ),
                ),
                (
                    "frais_plateforme",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais plateforme",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_mobiles",
                        to="sales.vente",
                        verbose_name="Vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement mobile",
                "verbose_name_plural": "Paiements mobiles",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Remboursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "numero_remboursement",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de remboursement",
                    ),
                ),
                (
                    "montant_demande",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant demandé"
                    ),
                ),
                (
                    "montant_approuve",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Montant approuvé",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("defaut_produit", "Défaut produit"),
                            ("erreur_commande", "Erreur de commande"),
                            ("retard_livraison", "Retard de livraison"),
                            ("insatisfaction", "Insatisfaction client"),
                            ("erreur_paiement", "Erreur de paiement"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Motif",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demande", "Demandé"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("refuse", "Refusé"),
                            ("annule", "Annulé"),
                        ],
                        default="demande",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de demande"
                    ),
                ),
                (
                    "date_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "date_remboursement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de remboursement"
                    ),
                ),
                (
                    "notes_traitement",
                    models.TextField(blank=True, verbose_name="Notes de traitement"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "paiement_mobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remboursements",
                        to="payments.paiementmobile",
                        verbose_name="Paiement mobile",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remboursement",
                "verbose_name_plural": "Remboursements",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="LienPaiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=100, unique=True, verbose_name="Token"),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du lien")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XOF", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "operateurs_autorises",
                    models.JSONField(
                        default=list,
                        help_text="Liste des opérateurs autorisés",
                        verbose_name="Opérateurs autorisés",
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                (
                    "date_utilisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'utilisation"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("utilise", "Utilisé"),
                            ("expire", "Expiré"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_utilisations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'utilisations"
                    ),
                ),
                (
                    "max_utilisations",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre max d'utilisations"
                    ),
                ),
                (
                    "url_succes",
                    models.URLField(blank=True, verbose_name="URL de succès"),
                ),
                ("url_echec", models.URLField(blank=True, verbose_name="URL d'échec")),
                (
                    "url_annulation",
                    models.URLField(blank=True, verbose_name="URL d'annulation"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_paiement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrepreneur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de paiement",
                "verbose_name_plural": "Liens de paiement",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddIndex(
            model_name="paiementmobile",
            index=models.Index(
                fields=["vente", "statut"], name="payments_pa_vente_i_e7d48c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementmobile",
            index=models.Index(
                fields=["operateur", "statut"], name="payments_pa_operate_35f5b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementmobile",
            index=models.Index(
                fields=["reference_transaction"], name="payments_pa_referen_ac3201_idx"
            ),
        ),
    ]
