# Generated by Django 4.2.7 on 2025-09-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSupport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "numero_ticket",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de ticket"
                    ),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="Sujet")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("technique", "Technique"),
                            ("facturation", "Facturation"),
                            ("produit", "Produit"),
                            ("livraison", "Livraison"),
                            ("compte", "Compte"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("en_attente_client", "En attente client"),
                            ("resolu", "Résolu"),
                            ("ferme", "Fermé"),
                            ("escalade", "Escaladé"),
                        ],
                        default="ouvert",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "date_resolution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de résolution"
                    ),
                ),
                (
                    "date_fermeture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fermeture"
                    ),
                ),
                (
                    "note_satisfaction",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Note de satisfaction",
                    ),
                ),
                (
                    "commentaire_satisfaction",
                    models.TextField(
                        blank=True, verbose_name="Commentaire satisfaction"
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "temps_resolution",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Temps de résolution"
                    ),
                ),
                (
                    "assigne_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assignes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de support",
                "verbose_name_plural": "Tickets de support",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ReponseTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type_reponse",
                    models.CharField(
                        choices=[
                            ("reponse", "Réponse"),
                            ("note_interne", "Note interne"),
                            ("solution", "Solution"),
                        ],
                        default="reponse",
                        max_length=20,
                        verbose_name="Type de réponse",
                    ),
                ),
                (
                    "visible_client",
                    models.BooleanField(
                        default=True, verbose_name="Visible par le client"
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="support.ticketsupport",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse ticket",
                "verbose_name_plural": "Réponses ticket",
                "ordering": ["date_creation"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_feedback",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("suggestion", "Suggestion"),
                            ("plainte", "Plainte"),
                            ("compliment", "Compliment"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de feedback",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "note_globale",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Note globale",
                    ),
                ),
                ("traite", models.BooleanField(default=False, verbose_name="Traité")),
                (
                    "date_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                ("reponse", models.TextField(blank=True, verbose_name="Réponse")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "traite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks_traites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback client",
                "verbose_name_plural": "Feedbacks client",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Question")),
                ("reponse", models.TextField(verbose_name="Réponse")),
                (
                    "categorie",
                    models.CharField(max_length=50, verbose_name="Catégorie"),
                ),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "nombre_consultations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de consultations"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["ordre_affichage", "question"],
            },
        ),
        migrations.CreateModel(
            name="BaseConnaissance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "contenu_html",
                    models.TextField(blank=True, verbose_name="Contenu HTML"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("guide", "Guide"),
                            ("tutoriel", "Tutoriel"),
                            ("troubleshooting", "Dépannage"),
                            ("api", "Documentation API"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                ("mots_cles", models.JSONField(default=list, verbose_name="Mots-clés")),
                ("public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "nombre_vues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "nombre_likes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de likes"
                    ),
                ),
                (
                    "utile_count",
                    models.PositiveIntegerField(default=0, verbose_name="Votes utiles"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article base de connaissances",
                "verbose_name_plural": "Articles base de connaissances",
            },
        ),
        migrations.AddIndex(
            model_name="ticketsupport",
            index=models.Index(
                fields=["utilisateur", "statut"], name="support_tic_utilisa_39a16f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketsupport",
            index=models.Index(
                fields=["assigne_a", "statut"], name="support_tic_assigne_56d9cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketsupport",
            index=models.Index(
                fields=["priorite", "date_creation"],
                name="support_tic_priorit_25e12a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baseconnaissance",
            index=models.Index(
                fields=["categorie", "public"], name="support_bas_categor_51d789_idx"
            ),
        ),
    ]
