# Generated by Django 4.2.7 on 2025-09-15 16:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "__first__"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du bundle")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "prix_bundle",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix du bundle",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "en_promotion",
                    models.BooleanField(default=False, verbose_name="En promotion"),
                ),
                (
                    "date_debut_promotion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début promotion"
                    ),
                ),
                (
                    "date_fin_promotion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin promotion"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle",
                "verbose_name_plural": "Bundles",
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="Image"
                    ),
                ),
                (
                    "icone",
                    models.CharField(blank=True, max_length=50, verbose_name="Icône"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#6B7280", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="Visible")),
                (
                    "meta_titre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta titre"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta description"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_categories",
                        to="products.categorie",
                        verbose_name="Catégorie parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["ordre_affichage", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "contact_nom",
                    models.CharField(max_length=100, verbose_name="Nom du contact"),
                ),
                (
                    "contact_fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction du contact"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "telephone_secondaire",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone secondaire"
                    ),
                ),
                (
                    "conditions_paiement",
                    models.CharField(
                        max_length=200, verbose_name="Conditions de paiement"
                    ),
                ),
                (
                    "delai_livraison",
                    models.PositiveIntegerField(
                        verbose_name="Délai de livraison (jours)"
                    ),
                ),
                (
                    "montant_minimum_commande",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant minimum de commande",
                    ),
                ),
                (
                    "evaluation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Évaluation",
                    ),
                ),
                (
                    "nombre_evaluations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'évaluations"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_commandes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de commandes"
                    ),
                ),
                (
                    "montant_total_commandes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant total des commandes",
                    ),
                ),
                (
                    "adresse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.adresse",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="marques/", verbose_name="Logo"
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "pays_origine",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pays d'origine"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marque",
                "verbose_name_plural": "Marques",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description_courte",
                    models.CharField(max_length=500, verbose_name="Description courte"),
                ),
                (
                    "description_longue",
                    models.TextField(blank=True, verbose_name="Description longue"),
                ),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "code_barre",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Code-barres",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, upload_to="qr_codes/", verbose_name="QR Code"
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix de vente",
                    ),
                ),
                (
                    "prix_promotion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix promotionnel",
                    ),
                ),
                (
                    "tva_taux",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "unite_mesure",
                    models.CharField(
                        choices=[
                            ("piece", "Pièce"),
                            ("kg", "Kilogramme"),
                            ("g", "Gramme"),
                            ("l", "Litre"),
                            ("ml", "Millilitre"),
                            ("m", "Mètre"),
                            ("cm", "Centimètre"),
                            ("m2", "Mètre carré"),
                            ("m3", "Mètre cube"),
                            ("pack", "Pack"),
                            ("carton", "Carton"),
                            ("palette", "Palette"),
                        ],
                        default="piece",
                        max_length=20,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=dict,
                        help_text='Dimensions en cm: {"longueur": 0, "largeur": 0, "hauteur": 0}',
                        verbose_name="Dimensions",
                    ),
                ),
                (
                    "couleurs_disponibles",
                    models.JSONField(
                        default=list,
                        help_text="Liste des couleurs disponibles",
                        verbose_name="Couleurs disponibles",
                    ),
                ),
                (
                    "tailles_disponibles",
                    models.JSONField(
                        default=list,
                        help_text="Liste des tailles disponibles",
                        verbose_name="Tailles disponibles",
                    ),
                ),
                (
                    "stock_minimum",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock minimum"
                    ),
                ),
                (
                    "stock_maximum",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Stock maximum"
                    ),
                ),
                (
                    "point_recommande",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Point de recommande"
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de péremption"
                    ),
                ),
                (
                    "duree_conservation",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée de conservation en jours",
                        null=True,
                        verbose_name="Durée de conservation",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("rupture", "Rupture de stock"),
                            ("discontinue", "Discontinué"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "popularite_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Score de popularité"
                    ),
                ),
                (
                    "nombre_vues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "nombre_ventes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de ventes"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "meta_titre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta titre"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta description"),
                ),
                (
                    "en_promotion",
                    models.BooleanField(default=False, verbose_name="En promotion"),
                ),
                (
                    "date_debut_promotion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début promotion"
                    ),
                ),
                (
                    "date_fin_promotion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin promotion"
                    ),
                ),
                (
                    "vendable",
                    models.BooleanField(default=True, verbose_name="Vendable"),
                ),
                (
                    "achetable",
                    models.BooleanField(default=True, verbose_name="Achetable"),
                ),
                (
                    "visible_catalogue",
                    models.BooleanField(
                        default=True, verbose_name="Visible dans le catalogue"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits",
                        to="products.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.entreprise",
                        verbose_name="Entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ProduitFournisseur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "quantite_minimum",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantité minimum"
                    ),
                ),
                (
                    "delai_livraison",
                    models.PositiveIntegerField(
                        verbose_name="Délai de livraison (jours)"
                    ),
                ),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False, verbose_name="Fournisseur principal"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit-Fournisseur",
                "verbose_name_plural": "Produits-Fournisseurs",
                "unique_together": {("produit", "fournisseur")},
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="fournisseurs",
            field=models.ManyToManyField(
                through="products.ProduitFournisseur",
                to="products.fournisseur",
                verbose_name="Fournisseurs",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="marque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.marque",
                verbose_name="Marque",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modifie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="sous_categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produits_sous_categorie",
                to="products.categorie",
                verbose_name="Sous-catégorie",
            ),
        ),
        migrations.CreateModel(
            name="ImageProduit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="produits/", verbose_name="Image"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Texte alternatif"
                    ),
                ),
                (
                    "principale",
                    models.BooleanField(default=False, verbose_name="Image principale"),
                ),
                (
                    "ordre_affichage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "couleur",
                    models.CharField(blank=True, max_length=50, verbose_name="Couleur"),
                ),
                (
                    "taille",
                    models.CharField(blank=True, max_length=50, verbose_name="Taille"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image produit",
                "verbose_name_plural": "Images produit",
                "ordering": ["ordre_affichage"],
            },
        ),
        migrations.CreateModel(
            name="BundleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.bundle",
                        verbose_name="Bundle",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de bundle",
                "verbose_name_plural": "Items de bundle",
            },
        ),
        migrations.CreateModel(
            name="VarianteProduit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "supprime",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "couleur",
                    models.CharField(blank=True, max_length=50, verbose_name="Couleur"),
                ),
                (
                    "taille",
                    models.CharField(blank=True, max_length=50, verbose_name="Taille"),
                ),
                (
                    "materiau",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Matériau"
                    ),
                ),
                (
                    "prix_supplement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Supplément de prix",
                    ),
                ),
                (
                    "sku_variante",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="SKU variante"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cree",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modifie",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante produit",
                "verbose_name_plural": "Variantes produit",
                "unique_together": {("produit", "couleur", "taille")},
            },
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["entreprise", "statut"], name="products_pr_entrepr_635320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["categorie", "statut"], name="products_pr_categor_d4e54f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(fields=["sku"], name="products_pr_sku_8f5d43_idx"),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["code_barre"], name="products_pr_code_ba_7ef6e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["popularite_score"], name="products_pr_popular_cfdf8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["en_promotion", "date_fin_promotion"],
                name="products_pr_en_prom_188538_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imageproduit",
            index=models.Index(
                fields=["produit", "principale"], name="products_im_produit_796d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(
                fields=["entreprise", "statut"], name="products_fo_entrepr_848f1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(
                fields=["evaluation"], name="products_fo_evaluat_6d68c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorie",
            index=models.Index(
                fields=["parent", "visible"], name="products_ca_parent__55e370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorie",
            index=models.Index(fields=["slug"], name="products_ca_slug_7b4282_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="bundleitem",
            unique_together={("bundle", "produit")},
        ),
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(
                fields=["entreprise", "actif"], name="products_bu_entrepr_647ab7_idx"
            ),
        ),
    ]
