# Generated by Django 4.2.7 on 2025-09-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundle",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="bundle",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="bundleitem",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="bundleitem",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="categorie",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="categorie",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="fournisseur",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="fournisseur",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="imageproduit",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="imageproduit",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="marque",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="marque",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="produitfournisseur",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="produitfournisseur",
            name="modifie_par",
        ),
        migrations.RemoveField(
            model_name="varianteproduit",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="varianteproduit",
            name="modifie_par",
        ),
        migrations.AddField(
            model_name="bundle",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="bundle",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="bundleitem",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="bundleitem",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="categorie",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="categorie",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="imageproduit",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="imageproduit",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="marque",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="marque",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="produitfournisseur",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="produitfournisseur",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
        migrations.AddField(
            model_name="varianteproduit",
            name="cree_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du créateur"
            ),
        ),
        migrations.AddField(
            model_name="varianteproduit",
            name="modifie_par_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID du modificateur"
            ),
        ),
    ]
