# Generated by Django 4.2.7 on 2025-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_bundle_cree_par_remove_bundle_modifie_par_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="code_barre",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Code-barres",
            ),
        ),
    ]
