# Generated by Django 4.2.7 on 2025-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_produit_code_barre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageproduit",
            name="image",
            field=models.URLField(max_length=500, verbose_name="Image"),
        ),
    ]
