# Generated by Django 4.2.7 on 2025-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_imageproduit_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageproduit",
            name="image",
            field=models.CharField(max_length=500, verbose_name="Image"),
        ),
    ]
