# Generated by Django 4.2.7 on 2025-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_imageproduit_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageproduit",
            name="image",
            field=models.ImageField(upload_to="produits/images/", verbose_name="Image"),
        ),
    ]
