# Generated by Django 4.2.7 on 2025-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_fix_image_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="poids",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="point_recommande",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="stock_maximum",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="stock_minimum",
        ),
        migrations.AddField(
            model_name="produit",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock"),
        ),
    ]
