# Generated by Django 4.2.7 on 2025-10-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_produit_dimensions_remove_produit_poids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageproduit",
            name="image",
            field=models.ImageField(upload_to="produits/", verbose_name="Image"),
        ),
    ]
