# Generated by Django 4.2.7 on 2025-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_imageproduit_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["visible_catalogue", "statut", "date_creation"],
                name="products_pr_visible_37d4e8_idx",
            ),
        ),
    ]
